@echo off
echo Starting backend server...
start cmd /k "cd backend && call venv\Scripts\activate && python manage.py runserver"
echo Starting frontend dev server...
start cmd /k "cd frontend && npm run dev"
echo Both servers are starting...